// app_react/src/components/Header.js
import React, { Component } from 'react'

import './Header.css';

export default class Header extends Component {
    render() {
        const { title } = this.props;
        return (
            <header id="main_header">
                <div className="header_content content">
                    <h3>{title}</h3>
                </div>
            </header>
        )
    }
}

// appAngular/src/app/components/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  @Input() title: string = "Header";

  ngOnInit() { }

}

<header id="main_header">
    <div class="header_content content">
        <h3>{{title}}</h3>
    </div>
</header>
