// appAngular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  term: string = "";

  constructor(private router: Router) { }

  ngOnInit() { }

  onFormSubmit(form) {
    if (!this.term.length) {
      alert("Informe um termo!");
      return false;
    }
    this.router.navigate([`lista/${this.term}`]);
  }

}

<app-header title="Home"></app-header>
<div id="home_content" class="content">
    <div class="home_form_container">
        <p>Informe um termo:</p>
        <form #formHome="ngForm" (ngSubmit)="onFormSubmit(formHome)">
            <input type="text" id="input_term" name="term" [(ngModel)]="term" />
            <button type="submit">Pesquisar</button>
        </form>
    </div>
</div>

// app_react/src/pages/Home.js
import React, { Component } from 'react';
import Header from '../components/Header';

import './Home.css';

class Home extends Component {

    state = {
        term: ''
    }

    async _onFormSubmit(evt) {
        evt.preventDefault();
        const { term } = this.state;
        if (!term.length) {
            alert("Informe um termo!");
            return false;
        }
        this.props.history.push(`/lista/${term}`);
    }

    render() {
        const { term } = this.state;

        return (
            <>
                <Header title="Home" />
                <div id="home_content" className="content">
                    <div className="home_form_container">
                        <p>Informe um termo:</p>
                        <form onSubmit={this._onFormSubmit.bind(this)}>
                            <input type="text" id="input_term" value={term} onChange={(evt) => {
                                this.setState({ term: evt.target.value });
                            }} />
                            <button type="submit">Pesquisar</button>
                        </form>
                    </div>
                </div>
            </>
        )
    }
}

export default Home;
